### ISSUE TITLE
Favourite names reappear sometimes

### ISSUE THREAD

**Issue by frosas** [Erwin6997/baby-names-react#7]
How to reproduce the bug:

1. Click on a name "Aashi", the name is marked as favourite
1. Click on the All or Female gender button, "Aashi" appears back in the list of (non-favourite) names. Same happens if you search by "Aashi" instead.

<img width="729" alt="Screenshot_2020-06-14_at_10_09_12" src="https://user-images.githubusercontent.com/50098/84589543-39820000-ae27-11ea-87f7-bbb70aa2d4ac.png">

**Comment by Erwin6997** [comment]
yes this id new bug :)))

**Comment by Erwin6997** [comment]
I fixed this

**Comment by frosas** [comment]
This works as expected now 👍

**Comment by frosas** [comment]
Hmm, I noticed the name still appears in two places when you also search by name:

<img width="1253" alt="Screenshot_2020-06-21_at_18_10_34" src="https://user-images.githubusercontent.com/50098/85230865-e1c93300-b3ea-11ea-9d8e-1c2de400a58e.png">
